language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - ci/install.sh
  - ci/install_pyqt.sh

script: python setup.py test